[project]
authors = ["pipe99g <andres99ga@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Bayesiana_parcial_2"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
typer = ">=0.15.1,<0.16"
loguru = ">=0.7.2,<0.8"
tqdm = ">=4.67.1,<5"
matplotlib = ">=3.10.0,<4"
pandas = ">=2.2.3,<3"
seaborn = ">=0.13.2,<0.14"
numpy = ">=2.2.2,<3"
ipython = ">=8.32.0,<9"
xlrd = ">=2.0.1,<3"
geopandas = ">=1.0.1,<2"
